### ISSUE TITLE
pixel_to_world cannot extrapolate RA and Dec beyond image dimension?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/gwcs#240]
In pursuing ejeschke/ginga#781 and spacetelescope/stginga#155, I found that RA and Dec are `nan` when I provide pixels outside of image bounds. This is not the case for FITS WCS. Is this a bug or feature?

JWST image: https://stsci.box.com/s/hwrc5reqygmmv2rl3yvvz90l7ryjac6h

Using dev versions of `gwcs`, `asdf`, `astropy`, and `jwst`.

```python
from jwst import datamodels
dm = datamodels.open(filename)
w = dm.meta.wcs
w.pixel_to_world(-1, 0)
```

gives

```
<SkyCoord (ICRS): (ra, dec) in deg
    (nan, nan)>
```

For completeness, here is the FITS WCS output from the same file.

```python
from astropy.io import fits
from astropy.wcs import WCS

with fits.open(filename) as pf:
    w2 = WCS(pf[1].header)
    print(w2.pixel_to_world(-1, 0))
```

gives

```
<SkyCoord (ICRS): (ra, dec) in deg
    (80.65257753, -69.50583771)>
```

**Comment by nden** [comment]
GWCS has a `bounding_box` attribute which defines the range of acceptable inputs.  A flag controls how to evaluate the transforms. The default evaluation of the WCS is
```
WCS(*args, with_bounding_box=True)
```
This returns `NaN` for inputs outside the bounding box. If you want to extrapolate, pass the value of `False`.  The same concept can be applied to FITS WCS but is currently missing. FITS WCS always returns values even outside the validity of the WCS model.

APE 14 specifies that the low-level `pixel_to_world_values` method may return `NaN` where the WCS is not defined. This is not mentioned for the high-level methods which is probably an omission. In any case there's no way to pass flags to the high- or low- level methods in APE 14. 

Feel free to close this issue if this answers your question.

**Comment by pllim** [comment]
Thanks, Nadia! I have opened an issue at astropy/astropy-APEs#53
