### ISSUE TITLE
Remove astropy-helpers

### ISSUE THREAD

**Issue by nden** [spacetelescope/gwcs#244]

**Comment by Cadair** [comment]
I am happy to take a pass at this if you want.

The main thing that would change is that `setup.py test` and `setup.py build_docs` would no longer work.

**Comment by sosey** [comment]
you can copy the build_docs stuff from jwst or imexam. You basically just need the stuff around the BuildSphinx class,  just remove the extra build stuff: https://github.com/spacetelescope/imexam/blob/master/setup.py#L58. It's linked in imexam as build_sphinx, but easy enough to change that to build_docs

**Comment by Cadair** [comment]
Yeah that's one option. Interesting you wanted to keep it around, in SunPy and in the APE we propose to just get everyone to use `tox -e build_docs` instead.

*(I think the idea is to have packages print out the new command when you run the old ones)*

**Comment by sosey** [comment]
I never used the astropy helpers one, and i have C code that needs to compile ahead of time to be available for the doc build, this lets me specify that pretty easy.

**Comment by nden** [comment]
@Cadair Thanks! I'd rather do it myself as I expect to maintain it. But I'd appreciate a review.

**Comment by nden** [comment]
fixed in #249 and #255
