### ISSUE TITLE
Stokes Lookup Table needs to round down

### ISSUE THREAD

**Issue by Cadair** [spacetelescope/gwcs#266]
If I set up a `WCS` like this, so that the integer pixel coordinates are in the centre of the pixels.

```python
gw = WCS(Tabular1D(np.arange(-0.5, 3.5), [0, 1, 2, 3], bounds_error=False, method="nearest"),
         output_frame=cf.StokesFrame())
```

When you do this:
```python
inp = np.arange(-0.5, 4.0, 0.5)
list(zip(inp, gw(inp)))
[(-0.5, 0.0),
 (0.0, 0.0),
 (0.5, 1.0),
 (1.0, 1.0),
 (1.5, 2.0),
 (2.0, 2.0),
 (2.5, 3.0),
 (3.0, nan),
 (3.5, nan)]
```
the results are offset by +0.5 because of the interpolation. We need to be doing a `np.floor` rather than nearest.

**Comment by nden** [comment]
We discussed offline that given that pixels go from `[-0.5, 0.5)` the above result looks correct. @Cadair please close the ticket if you think there's no problem.

**Comment by Cadair** [comment]
I think this might be actually be a WCSAxes issue, I will confirm and then close this.

**Comment by Cadair** [comment]
This is now obsoleted by #452
