### ISSUE TITLE
documentation clarification

### ISSUE THREAD

**Issue by nden** [spacetelescope/gwcs#281]
Needed clarifications in the documentation

- [ ] Clarify that `WCS.forward_transform` is computed every time. This means the `is` operator cannot be used to compare when serializing to file.

- [ ] Clarify that `WCS.forward_transform.inverse = WCS.backward_transform` but `WCS.backward_transform.inverse = WCS.forward_transform` only if there are no custom inverses, i.e. the inverse of all constituent inverses are analytical. It's the same rule as modeling.

**Comment by perrygreenfield** [comment]
Do you mean the documentation as in the index.rst file, or the API docs? (I'm guessing the latter).

**Comment by nden** [comment]
Perhaps `using_wcs` is the place for these comments. I believe the second comment does not apply any more, after #405

**Comment by perrygreenfield** [comment]
OK

**Comment by perrygreenfield** [comment]
Closed with #483
