### ISSUE TITLE
world_to_pixel fails when input_frame is None

### ISSUE THREAD

**Issue by larrybradley** [spacetelescope/gwcs#294]
`world_to_pixel` fails when `input_frame` is None.  I'm seeing this for NIRCam, MIRI, and FGS `i2d` images generated by the `jwst` pipeline test suite:

```python
>>> from jwst import datamodels
>>> filepath = 'jw42424-o002_t001_nircam_clear-f444w_i2d.fits'
>>> model = datamodels.open(filepath)
>>> wcs = model.meta.wcs
>>> skycoord = wcs.pixel_to_world(100, 100)
>>> wcs.world_to_pixel(skycoord)
~/.venvs/jwst-dev/lib/python3.7/site-packages/gwcs/api.py in world_to_pixel(self, *world_objects)
    316         if not utils.isnumerical(result[0]):
    317             result = [i.value for i in result]
--> 318         if self.input_frame.naxes == 1:
    319             return result[0]
    320         return result

AttributeError: 'NoneType' object has no attribute 'naxes'
```

`wcs.input_frame` is indeed `None` for this file.  The same error occurs with
MIRI (`det_image_1_MIRIMAGE_F770Wexp1_5stars_i2d.fits`) and FGS (`jw86500007001_02101_00001_GUIDER2_i2d.fits`).

Is there an issue with the pipeline, i.e. should `input_frame` be set, or is this a `gwcs` bug?  I assume there is a round-trip test in `gwcs`, but perhaps not one where `input_frame` is `None`.

**Comment by larrybradley** [comment]
`input_frame` is a `gwcs`-specific attribute (`astropy`/FITS wcs doesn't have it), so this is `gwcs` bug.

**Comment by nden** [comment]
If you want to have full functionality both input and output frame need to be set. This is not required in gwcs now as it much faster to play with it and test if you are interested in the transforms only. I believe the docs mention it. In any case I think it should be fixed in the pipeline and gwcs.

**Comment by jdavies-st** [comment]
This is probably where it needs to be fixed.

https://github.com/spacetelescope/jwst/blob/2d118dca27f931c1b9216914385ee38f0d0d6658/jwst/assign_wcs/util.py#L155-L156

We currently only provide an output frame.  Perhaps when this was originally written we didn't have a `Frame2D` input frame available?

**Comment by jdavies-st** [comment]
And the fix in `gwcs` might be in `wcs_from_fiducial()`.

https://github.com/spacetelescope/gwcs/blob/39da23da5b12383aeb6c290a4d7d9ba759bc89a7/gwcs/wcstools.py#L21-L22
