### ISSUE TITLE
RTD "latest" documentation is way too old

### ISSUE THREAD

**Issue by mcara** [spacetelescope/gwcs#314]
As of today, `gwcs` version `0.13.0` has been released. However, clicking on https://gwcs.readthedocs.io/en/latest/ takes me to documentation for `gwcs v0.10.1.dev468`. Something is not set-up correctly in RTD (maybe it is set to build from an old branch?)

CC: @nden

**Comment by eslavich** [comment]
I manually built `0.13.0` and the latest master, should I set up automatic builds similar to what we have for asdf?

**Comment by nden** [comment]
I'm not sure what happened but yes we need automatic builds on readthedocs.

**Comment by eslavich** [comment]
Do we want "latest" to be the most recently released version, or should it keep up with master?

**Comment by mcara** [comment]
@eslavich Thanks!
