### ISSUE TITLE
RTD versions

### ISSUE THREAD

**Issue by larrybradley** [spacetelescope/gwcs#321]
The RTD "stable" version still points to 0.10, instead of 0.14.0.  And there is no 0.14.0 version.  The current RTD versions are:

* master (is this needed?  it's the same as "latest")
* lastest
* stable
* 0.13.0 (outdated)
* 0.8.0 (outdated)

**Comment by mcara** [comment]
Isn't this kind of a duplicate of or related to https://github.com/spacetelescope/gwcs/issues/314 ?

**Comment by eslavich** [comment]
I can finish setting up the automation, I just need an answer to this question:

> Do we want "latest" to be the most recently released version, or should it keep up with master?

**Comment by larrybradley** [comment]
"Latest" usually points to the latest master and "Stable" points to the most recently released version.

**Comment by mcara** [comment]
I think for external users RTD link in the repository(ies) should point to the "stable". For developers, "latest" is more useful but they can dig through docstrings, if they need cutting-edge unreleased features .

**Comment by eslavich** [comment]
Alright "latest" now points to master, "stable" to the stable branch, and both should build automatically going forward.  I had to clear my browser to see the updated stable docs showing 0.14.0.

**Comment by larrybradley** [comment]
Thanks, @eslavich.
