### ISSUE TITLE
The format/type of the output of __call__ and invert differ

### ISSUE THREAD

**Issue by mcara** [spacetelescope/gwcs#326]
Here is a brief test that illustrates the issue:
```python
from jwst.datamodels import open as opendm
m = opendm('nrca5_47Tuc_subpix_dither1_newpos_assignwcsstep.fits')
w = m.meta.wcs
print(repr(w(1, 2)))
print(repr(w.invert(*w(1, 2))))
print(repr(w([1], [2])))
print(repr(w.invert(*w([1], [2]))))
```
producing the following output:
```python
[array(5.92762673), array(-72.01339464)]
(1.0156842040173615, 2.0076629609087604)
[array([5.92762673]), array([-72.01339464])]
(array([1.0156842]), array([2.00766296]))
```
So, while the forward transformation produces _lists_ of coordinates, the inverse transformation returns _tuples_ of coordinates. Moreover, when input coordinates are plain numbers, forward transformation returns _lists of **0-dim arrays**_ while the inverse transformation returns _tuples of **numbers**_.

While these differences may not have any practical consequences, I think it would be less confusing if both functions could return similar types of results.

**Comment by mcara** [comment]
@perrygreenfield With regard to the issue of having default inverse to be the analytical inverse if provided - see the very low accuracy of analytical inverse (~0.02 pix).

**Comment by jdavies-st** [comment]
Yeah, there's an asymmetry here.  For the transforms themselves though, they show symmetry:

`__call__` calls `forward_transform` after some setup.  It's inverse analog is `backwards_transform`.

```
In [1]: from jwst import datamodels

In [2]: model = datamodels.open("/Users/jdavies/Downloads/jw00617082001_02102_00001_nrcb2_cal.fits")

In [3]: wcs = model.meta.wcs

In [4]: wcs.forward_transform(1, 2)
Out[4]: (177.43287108116664, 50.17782038244915)

In [5]: wcs.backward_transform(*wcs.forward_transform(1, 2))
Out[5]: (0.991884560151334, 1.9713088467419766)
```

Also, the uncertainty in pixel values for these NIRCam files is not related to analytic inverses.  The inverses on the transforms are explicitly defined by the instrument teams and are not analytic.

**Comment by mcara** [comment]
Ah, also, adding/removing `bounding_box` changes the output format. For example in my first example above, do the following:
```python
print(repr(w(1, 2)))
w.bounding_box = None
print(repr(w(1, 2)))
```
Output:
```python
[array(5.92762673), array(-72.01339464)]
(5.927626726432927, -72.01339464326408)
```

**Comment by braingram** [comment]
The output using gwcs main differs from that described in this issue.

Using `jw00617082001_02102_00001_nrcb2_cal.fits` and running the following:
```python
print(repr(w(1, 2)))
print(repr(w.invert(*w(1, 2))))
print(repr(w([1], [2])))
print(repr(w.invert(*w([1], [2]))))
```
with gwcs main yields:
```
(177.43287108116664, 50.17782038244915)
(0.9918845607879803, 1.9713088455096113)
(array([177.43287108]), array([50.17782038]))
(array([0.99188456]), array([1.97130885]))
```

**Comment by Cadair** [comment]
@braingram and I tested this and don't think it's still a problem. Close?

**Comment by braingram** [comment]
@mcara feel free to reopen and update this if the issue isn't addressed.

**Comment by mcara** [comment]
Thanks!
