### ISSUE TITLE
Documentation/Example for IFU does not work

### ISSUE THREAD

**Issue by mcara** [spacetelescope/gwcs#350]
The example from https://gwcs.readthedocs.io/en/latest/gwcs/ifu.html?highlight=SpectralFrame does not work because `mask` is undefined when creating `selector.RegionsSelector`. Just a line or two up, it says:
```
Assuming the array is stored in ASDF format, create the mask:
```
but the code to create the mask is missing.

**Comment by perrygreenfield** [comment]
Closed by #483
