### ISSUE TITLE
Dev GWCS breaks specutils tests

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/gwcs#378]
Hi all, I'm testing the astropy 5.0 release candidate and talking to @WilliamJamieson about some errors I've been encountering. It turns out that the most recent dev version of GWCS fixes one of the specutils test failures (related to `bounding_box`), but causes a different failure to occur, with the traceback below (a sample of the ~10 failures). It looks like the units are getting dropped somewhere that they were being successfully preserved in 0.16.1. If you could let me know if this looks like a bug on the GWCS side or something we need to update in specutils, I would appreciate it.

```
_____________________________________________ test_correlation_random_lines _____________________________________________

    def test_correlation_random_lines():
        [cut for brevity]

        # Get result from correlation
>       corr, lag = correlation.template_correlate(spec1, spec2)

tests/test_correlation.py:240:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
analysis/correlation.py:72: in template_correlate
    observed_log_spectrum, template_log_spectrum = _apodize(log_spectrum,
analysis/correlation.py:118: in _apodize
    clean_spectrum = spectrum * window(len(spectrum.spectral_axis))
spectra/spectrum1d.py:556: in __mul__
    return self.multiply(other)
../../astropy/astropy/nddata/mixins/ndarithmetic.py:530: in multiply
    return self._prepare_then_do_arithmetic(np.multiply, operand, operand2,
../../astropy/astropy/nddata/mixins/ndarithmetic.py:610: in _prepare_then_do_arithmetic
    operand2 = cls(operand2)
spectra/spectrum1d.py:288: in __init__
    spec_axis = self.wcs.pixel_to_world(np.arange(self.flux.shape[-1]))
utils/wcs_utils.py:217: in pixel_to_world
    return super().pixel_to_world(*args, **kwargs).to(
../../gwcs/gwcs/api.py:299: in pixel_to_world
    return self(*pixels, with_units=True)
../../gwcs/gwcs/wcs.py:369: in __call__
    result = self.output_frame.coordinates(result)
../../gwcs/gwcs/coordinate_frames.py:463: in coordinates
    return coord.SpectralCoord(*args).to(self.unit[0])
../../astropy/astropy/units/decorators.py:304: in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)
../../astropy/astropy/coordinates/spectral_coordinate.py:193: in __new__
    obj = super().__new__(cls, value, unit=unit, **kwargs)
../../astropy/astropy/coordinates/spectral_quantity.py:57: in __new__
    obj = super().__new__(cls, value, unit=unit, **kwargs)
../../astropy/astropy/units/quantity.py:425: in __new__
    value = value.view(cls)
../../astropy/astropy/coordinates/spectral_coordinate.py:242: in __array_finalize__
    super().__array_finalize__(obj)
../../astropy/astropy/coordinates/spectral_quantity.py:72: in __array_finalize__
    super().__array_finalize__(obj)
../../astropy/astropy/units/quantity.py:550: in __array_finalize__
    self._set_unit(unit)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[AttributeError("SpectralCoord instance has no attribute 'radial_velocity'") raised in repr()] SpectralCoord object at 0x7fd4f0a83900>
unit = Unit(dimensionless)

    def _set_unit(self, unit):
        if unit is None or not unit.is_equivalent(self._equivalent_unit):
>           raise UnitTypeError(
                "{} instances require units equivalent to '{}'"
                .format(type(self).__name__, self._equivalent_unit) +
                (", but no unit was given." if unit is None else
                 f", so cannot set it to '{unit}'."))
E           astropy.units.core.UnitTypeError: SpectralCoord instances require units equivalent to '(Unit("Hz"), Unit("m"), Unit("J"), Unit("1 / m"), Unit("km / s"))', so cannot set it to ''.

../../astropy/astropy/units/quantity.py:1933: UnitTypeError
```

**Comment by nden** [comment]
This does look like a gwcs issue. It would be helpful to have a simple example that shows the inputs to the gwcs call.

**Comment by rosteen** [comment]
Ok, after some digging I have some more specific information about what is happening here. The problem occurs when a `Spectrum1D` is initialized without a `spectral_axis` or WCS input - this happens for example when multiplying a `Spectrum1D` by a unitless array, which on the backend will be turned into a unitless `Quantity` and then into a `Spectrum1D` by the [NDArithmetic machinery](https://github.com/astropy/astropy/blob/993cf238fe26fa543b31de0d147cd532d9d205e9/astropy/nddata/mixins/ndarithmetic.py#L610). 

In the case that a `Spectrum1D` is initialized without a WCS or `spectral_axis`, it creates an array of pixel values and feeds that into [gwcs_from_array](https://github.com/astropy/specutils/blob/d7507aa2353e9bbb718180ff2eaa2fdce21972ab/specutils/utils/wcs_utils.py#L185). The error I'm seeing is due to trying to use `pixel_to_world` on the GWCS object created there, which previously was happy to return a unitless Quantity but now errors due to requiring spectral units. You can reproduce this simply by creating a `Spectrum1D` with no WCS or `spectral_axis` specified:

```
from specutils import Spectrum1D
import numpy as np
import astropy.units as u

test = Spectrum1D(np.random.random(10)*u.Jy)
```

I note that we define a custom `pixel_to_world` method (see below) that uses spectral equivalencies, maybe the root of the issue is that unitless is no longer acceptable for that equivalency? Although I think the root cause is likely actually in `SpectralCoord`...

```
    class SpectralGWCS(GWCS):
        def pixel_to_world(self, *args, **kwargs):
            return super().pixel_to_world(*args, **kwargs).to(
                orig_array.unit, equivalencies=u.spectral())
```

**Comment by rosteen** [comment]
It seems like there are three options here for where to fix this:

1. Change `Spectrum1D` to use something other than `SpectralFrame` when creating a unitless "dummy" WCS/spectral axis. 
2. Change `SpectralFrame` to allow for unitless "spectral" frames.
3. Change `SpectralCoord` to allow the creation of a unitless "spectral" coordinate. 

On the one hand it seems weird to call something a spectral axis if the coordinates are unitless/pixels, but on the other hand we clearly have at least one use for doing so. I'm open to other suggestions, or opinions about which option is the best.

**Comment by nden** [comment]
GWCS on master uses now SpectralCoord.coordinates to return spectral coordinates, as opposed to quantities as done until 0.16.1, which is what is causing this error. Previously, [SpectralCoordFrame.coordinates](https://github.com/spacetelescope/gwcs/blob/0.16.1x/gwcs/coordinate_frames.py#L447) worked because it was converting dimensionless quantities to quantities. Now, after converting to the correct units it creates a `SpectralCoord` which requires that the Quantity has spectral units.

So I think that perhaps this is a conceptual issue since specutils is attempting to create a SpectralCoord object without spectral units. And potentially may affect the release if it is decided to relax the requirement for spectral units.

**Comment by rosteen** [comment]
CC @eteq @nmearl @keflavich, who might have some useful thoughts here.

**Comment by nden** [comment]
Another option is to "enhance" `SpectralGWCS` to call GWCS.pixel_to_world_values() in the presence of a dummy spectral axis.

**Comment by rosteen** [comment]
Great suggestion, I implemented it in https://github.com/astropy/specutils/pull/895 and will run it by the other specutils maintainers. All our tests are passing again with that PR and the most recent gwcs dev version and https://github.com/astropy/astropy/pull/12440.

**Comment by rosteen** [comment]
Closing this, since I merged the specutils PR resolving the problem. Thanks for the help!
