### ISSUE TITLE
GWCS does not always roundtrip

### ISSUE THREAD

**Issue by pllim** [spacetelescope/gwcs#392]
It roundtrips fine in your "getting started" example but in a real JWST file, it does not. I am not sure if this is related to asdf-format/asdf#1032 as it could also be a serialization issue but this one does not give me an error, it just does not roundtrip. Is this a bug or maybe I just don't understand how GWCS works?

```python
>>> from asdf.fits_embed import AsdfInFits
>>> from astropy.utils.data import download_file
>>> jwf277w = download_file('https://stsci.box.com/shared/static/iao1zxtigyrhq7k3wtu5nchrxzlhj9kv.fits', cache=True)
>>> af = AsdfInFits.open(jwf277w)
>>> wcsobj = af['meta']['wcs']
>>> x, y = 0, 0
>>> sky1 = wcsobj.pixel_to_world(x, y)
>>> sky1
<SkyCoord (ICRS): (ra, dec) in deg
    (80.53338789, -69.51439081)>
>>> x, y = wcsobj.world_to_pixel(sky1)
>>> x, y
(0.01591886290589173, 0.013368985437637093)
>>> sky2 = wcsobj.pixel_to_world(x, y)
>>> sky2
<SkyCoord (ICRS): (ra, dec) in deg
    (80.53338707, -69.51439057)>
```

I expect `sky1` and `sky2` to be the same but they are not. I noticed this while working on spacetelescope/jdaviz#945 with JWST files containing ASDF-in-FITS with GWCS.

EDIT: Version info as follows...

`numpy` 1.21.2
`astropy` 5.0
`asdf` 2.8.1
`gwcs` 0.17.0

**Comment by nden** [comment]
This is not a software problem. GWCS only evaluates the transforms. The calibration needs to be accurate enough to roundtrip. Hopefully in a few more months we'll have better defined distortion models.

**Comment by nden** [comment]
This kind of issues need to be filed in the jwst repository.
