### ISSUE TITLE
conda-forge release is outdated

### ISSUE THREAD

**Issue by pllim** [spacetelescope/gwcs#417]
I see you have unmerged https://github.com/conda-forge/gwcs-feedstock/pull/20 , which would have brought it up to date if fixed and merged. FYI.

**Comment by rosteen** [comment]
Note that the conda-forge builds are failing because `pkg_resources` is now used in `__init__.py` but isn't installed in the build.

**Comment by pllim** [comment]
I opened #418 about that too. 😸

**Comment by nden** [comment]
up to date now
