### ISSUE TITLE
You should not need pkg_resources at run time

### ISSUE THREAD

**Issue by pllim** [spacetelescope/gwcs#418]
https://github.com/spacetelescope/gwcs/blob/713a0bc710a80ff44ac711ceec1f02ceb51d591c/gwcs/__init__.py#L65-L69

See https://github.com/astropy/astropy/blob/b6352e194ab00de75f33f0b36ccb944333d20a10/astropy/__init__.py#L12

**Comment by nden** [comment]
Fixed in #478
