### ISSUE TITLE
How to use with_bounding_box=False in pixel_to_world and world_to_pixel ?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/gwcs#431]
I want to ignore the bounding box during forward and backward transformations using high-level API without actually changing the input GWCS `bounding_box` attribute permanently. Is this possible? It says the keyword is not recognized and https://gwcs.readthedocs.io/en/latest/gwcs/using_wcs.html#using-bounding-box is not very clear on when to use it.

**Comment by mcara** [comment]
Could you so kind as to provide a brief example that shows tbe keyword error?

**Comment by mcara** [comment]
Since `pixel_to_world` and `world_to_pixel` conform to APE 14 convention and since according to this comment:
https://github.com/astropy/astropy/issues/9073#issuecomment-517076210
they won't be supported any time soon.

**Comment by pllim** [comment]
Okay, thanks for the clarification!
