### ISSUE TITLE
Documentation refers to deprecated asdf.fits_embed

### ISSUE THREAD

**Issue by braingram** [spacetelescope/gwcs#453]
https://gwcs.readthedocs.io/en/latest/#save-a-wcs-object-as-an-asdf-extension-in-a-fits-file

Support for AsdfInFits has moved to stdatamodels:
https://stdatamodels.readthedocs.io/en/latest/asdf_in_fits.html

**Comment by perrygreenfield** [comment]
Addressed by #483
