### ISSUE TITLE
Deprecate the pre-APE 14 API

### ISSUE THREAD

**Issue by Cadair** [spacetelescope/gwcs#456]
I am looking through the code trying to get to the bottom of #455 and the tangled web of how the APE 14 API calls the `__call__` and `invert` methods which also have their own API semantics is driving me round the bend. Therefore I have the following proposal:

* Refactor the existing code so that there is an "internal" forward and backward transform method with a very restrictive API. (Takes Quantity if the transform uses quantities and returns whatever the transform returns, some extra handling for numerical inverse etc).
* Keep the current `__call__` and `invert` methods and deprecate them.
* Rework the APE 14 API methods so that they do any required pre- or post-processing before calling the "internal" forward and backward methods.

We could keep the old API deprecated for a long time (we don't even have to make it raise warnings or anything at this point), but I feel like there's no need to keep around both sets of API for a package which hasn't hit 1.0 yet?

**Comment by nden** [comment]
The API definitely needs to be cleaned up. I don't agree we should keep only the APE 14 API.

**Comment by Cadair** [comment]
What do you want to provide with the non-APE 14 API that is distinct from the APE 14 one? or is it just a stability thing?

**Comment by Cadair** [comment]
As much of this as is going to be done is done in #457
