### ISSUE TITLE
docs mention saving to AsdfInFits which is not available in asdf 3.0

### ISSUE THREAD

**Issue by braingram** [spacetelescope/gwcs#465]
Perhaps this section should be removed?
https://github.com/spacetelescope/gwcs/blob/929478d8152574699e57e5498a2e4c079583a1e4/docs/index.rst?plain=1#L250
Or alternatively the section could be updated to use stdatamodels:
https://stdatamodels.readthedocs.io/en/latest/asdf_in_fits.html#writing-asdfinfits-files

**Comment by perrygreenfield** [comment]
Does the reading of the WCS from a FITS extension still work (line 260)?

**Comment by braingram** [comment]
Neither reading nor writing to fits works with asdf 3.0 as support for `AsdfInFits` was dropped.

Which line are you referring to for `reading of the WCS from a FITS extension`? Line 260 in `docs/index.rst` appears to be writing to a fits extension. Are you referring to a different file?

https://github.com/spacetelescope/gwcs/blob/929478d8152574699e57e5498a2e4c079583a1e4/docs/index.rst?plain=1#L259-L261

The following section in `docs/index.rst` that refers to reading from a fits extension (using asdf) is another example of something that no longer works in asdf 3.0:
https://github.com/spacetelescope/gwcs/blob/929478d8152574699e57e5498a2e4c079583a1e4/docs/index.rst?plain=1#L283-L288

**Comment by perrygreenfield** [comment]
For now I just removed all that FITS stuff (both reading and writing examples from and to FITS extensions). I'd rather not pull in stdatamodels in this. If we have a more generic way of dealing with ASDF in FITS extensions, we can but it back in, but for now let's leave it out.

**Comment by perrygreenfield** [comment]
Addressed by #483
