### ISSUE TITLE
Bug in backward_transform

### ISSUE THREAD

**Issue by izkgao** [spacetelescope/gwcs#511]
I tried to check if a coordinate is inside a WCS (jw01837003010_04201_00001_nrcblong, after TweakReg), but it gives a wrong result, while the astropy fits wcs converted from gwcs gives the correct result.

```python
import asdf
from astropy.wcs import WCS

with asdf.open('test.asdf') as af:
    wcs = af.tree['wcs']

print(wcs.in_image(150.200, 2.210))
# True
fits_wcs = WCS(wcs.to_fits_sip())
print(fits_wcs.footprint_contains(SkyCoord(ra=150.200, dec=2.210, unit='deg')))
# False

print(wcs.backward_transform(150.200, 2.210))
# (763.3177190034882, 595.2616574347967)
print(wcs.forward_transform(*wcs.backward_transform(150.200, 2.210)))
# (150.108379118644, 2.3911705306532)
```
[test.asdf.zip](https://github.com/user-attachments/files/16995456/test.asdf.zip)

The four blue points are the footprint, and the orange point is the target, which is outside the footprint.

![image](https://github.com/user-attachments/assets/9b8920f9-e2b4-4b4f-bc74-ed2965dbdd41)

**Comment by nden** [comment]
Fixed in #498 and #536
