### ISSUE TITLE
Need a new gwcs release

### ISSUE THREAD

**Issue by pllim** [spacetelescope/gwcs#539]
@rosteen and I have been waiting for a new GWCS release for a few weeks because it is failing specutils CI. Any chance a release can be done soon? 🙏 

Thanks!

* https://github.com/spacetelescope/gwcs/pull/526

**Comment by Cadair** [comment]
Not until #457 is merged though :stuck_out_tongue_winking_eye:

**Comment by mcara** [comment]
#539

**Comment by pllim** [comment]
(Sorry, @Cadair !)
